version: 2
registries:
  docker-registry-registry-hub-docker-com:
    type: docker-registry
    url: https://registry.hub.docker.com
    username: rzpdependabot
    password: "${{secrets.DOCKER_REGISTRY_REGISTRY_HUB_DOCKER_COM_PASSWORD}}"
  docker-registry-c-rzp-io:
    type: docker-registry
    url: https://c.rzp.io
    username: kranti.deep@razorpay.com
    password: "${{secrets.DOCKER_REGISTRY_C_RZP_IO_PASSWORD}}"

updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Asia/Calcutta
  ignore:
  - dependency-name: alpine
    versions:
    - 3.13.0
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
  registries:
  - docker-registry-registry-hub-docker-com
  - docker-registry-c-rzp-io
