apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-backup
  namespace: kube-system 
data:
  ETCD_CA_PATH: "/etc/kubernetes/secrets/etcd-client-ca.crt"
  ETCD_CERT_PATH: "/etc/kubernetes/secrets/etcd-client.crt"
  ETCD_KEY_PATH: "/etc/kubernetes/secrets/etcd-client.key"
  ETCD_ENDPOINTS: "etcd.cluster.com"
  S3_BUCKET_NAME: "kubernetes"
  CLUSTER_NAME: test
